"""Render an InvestigationReport as deterministic Markdown.

Consumes only the structured report. Does not import or call investigation
engine functions. Empty Version 1.1 expansion sections are omitted so the
current human-readable report shape stays intact.
"""

from __future__ import annotations

from typing import Any

from reports.models import InvestigationReport

_QUERY_GROUP_TITLES = {
    "qradar_aql": "QRadar AQL",
    "sentinel_kql": "Microsoft Sentinel KQL",
    "defender_advanced_hunting_kql": "Microsoft Defender Advanced Hunting KQL",
    "opensearch_dql": "OpenSearch / DQL",
}


def _bullet_list(items: list[Any]) -> str:
    if not items:
        return "_None provided._"
    lines = []
    for item in items:
        text = str(item).strip()
        lines.append(f"- {text}" if text else "-")
    return "\n".join(lines)


def _render_mitre(report: InvestigationReport) -> str:
    mappings = report.mitre
    if not mappings:
        return "_No MITRE ATT&CK mappings returned._"

    sections: list[str] = []
    for mapping in mappings:
        sections.append(
            "\n".join(
                [
                    f"- **Technique ID:** {mapping.technique_id}",
                    f"- **Technique name:** {mapping.technique_name}",
                    f"- **Tactic:** {mapping.tactic}",
                    f"- **Confidence:** {mapping.confidence}",
                    f"- **Rationale:** {mapping.rationale}",
                ]
            )
        )
    return "\n\n".join(sections)


def _render_queries(report: InvestigationReport) -> str:
    recommended_queries = report.recommended_queries
    if not recommended_queries:
        return "_No recommended investigation queries returned._"

    sections: list[str] = []
    for key, queries in recommended_queries.items():
        title = _QUERY_GROUP_TITLES.get(key, key)
        sections.append(f"### {title}")
        if not queries:
            sections.append("_No queries in this group._")
            continue
        for query in queries:
            sections.append(f"```text\n{query}\n```")
    return "\n\n".join(sections)


def render_markdown(report: InvestigationReport) -> str:
    """Build the SOC Investigation Report Markdown from a structured report."""
    alert = report.alert
    summary = report.summary or "_No executive summary returned._"
    severity_assessment = (
        report.severity_assessment or "_No severity assessment returned._"
    )

    parts = [
        f"# {report.metadata.title}",
        "",
        "## Alert Overview",
        f"- **Platform:** {alert.platform}",
        f"- **Alert type:** {alert.alert_type}",
        f"- **Vendor severity:** {alert.severity}",
        f"- **Confidence:** {report.confidence}",
        "",
        "## Executive Summary",
        "",
        summary,
        "",
        "## Severity Assessment",
        "",
        severity_assessment,
        "",
        "## MITRE ATT&CK Mapping",
        "",
        _render_mitre(report),
        "",
        "## Recommended Investigation Queries",
        "",
        _render_queries(report),
        "",
        "## Next Investigation Steps",
        "",
        _bullet_list(report.next_steps),
        "",
        "## Detection Engineering Opportunities",
        "",
        _bullet_list(report.detection_opportunities),
        "",
        "## Analysis Limitations",
        "",
        _bullet_list(report.limitations),
        "",
        "---",
        "",
        f"Generated by the {report.metadata.generator}.",
        "",
    ]

    # Future Version 1.1 sections: omit when empty to avoid malformed / noisy Markdown.
    if report.evidence:
        parts.extend(
            [
                "## Evidence",
                "",
                _bullet_list(
                    [
                        f"{item.label}: {item.value}"
                        + (f" ({item.source})" if item.source else "")
                        for item in report.evidence
                    ]
                ),
                "",
            ]
        )
    if report.timeline:
        parts.extend(
            [
                "## Timeline",
                "",
                _bullet_list(
                    [
                        (
                            f"{event.timestamp}: {event.description}"
                            if event.timestamp
                            else event.description
                        )
                        for event in report.timeline
                    ]
                ),
                "",
            ]
        )
    if report.analyst_reasoning:
        parts.extend(
            [
                "## Analyst Reasoning",
                "",
                report.analyst_reasoning,
                "",
            ]
        )
    if report.confidence_rationale:
        parts.extend(
            [
                "## Confidence Rationale",
                "",
                report.confidence_rationale,
                "",
            ]
        )
    if report.disposition is not None:
        disposition_lines = [
            f"- **Recommendation:** {report.disposition.recommendation}",
        ]
        if report.disposition.rationale:
            disposition_lines.append(
                f"- **Rationale:** {report.disposition.rationale}"
            )
        parts.extend(
            [
                "## Disposition",
                "",
                "\n".join(disposition_lines),
                "",
            ]
        )

    return "\n".join(parts)
